#!/usr/bin/python
# -*- coding: utf-8 -*-

def gen_subject(from_file, dest_dir):
    """Generate subject from original file output to to_dir

    :from_file: original file
    :dest_dir: destination directory
    :returns: subject count

    """
    pass

def gen_answer(from_file, dest_file):
    """Generate answer from original file output to to_file

    :from_file: original file
    :dest_file: destination answer dict file
    :returns: answer count

    """
    pass

def currect_answer(from_file, standard_answer_file, dest_file):
    """Correct  answer from candidate file and standard answer_file

    :from_file: candidate file
    :standard_answer: standard file generated by gen_answer
    :dest_file: destination file
    :returns: answer count

    """
    pass



